### ISSUE TITLE
Support for smaller sweep data points/steps than 112

### ISSUE THREAD

**Issue by fviard** [RFExplorer/RFExplorer-for-Python#12]
I have a **RF Explorer 3G+ IoT** board to that i'm evaluating to be use with the python sdk.

Based on the documentation and what is enforced by the device, sweep data points minimum value is 112.

A full scan of 112 steps in my case takes around 350/400ms.
But I'm just interested in the amplitude value at a specific frequency step.
Step 56, or steps [50:60]

So, with keeping a similar step size, couldn't it be possible in some way for me to scan/retrieve fewer data point steps? like 1 or 10.
And so that the scan is faster because it doesn't have to scan >100 other steps?

Thank you

**Comment by arocholl** [comment]
Hi, you can use zero span mode (currently in beta) to scan only a single point. If you are interested in that mode, please open a request in https://support.rf-explorer.com

You can also increase scan speed by using fast mode, if you are ok with some potential spurs being detected. You can easily figure out if the frequency range has spur by comparing Filter and Fast mode and decide based on that. See SetDSP command for more details.

**Comment by Ryanf55** [comment]
I emailed support and they said that feature was still planned. Right now I am using a scan of 2mHz span in my 6G model and assuming the max is close to the power at the center. It takes longer to scan than I would prefer, even in fast mode. Is there functionality to pull power levels from the scan that are not mins or max powers? I followed along the supplied python USB example 2. Unfortunately, I can't find a way to get the data from `objSweepTemp` other than the max power and corresponding frequency. Any tips?

Frequencies of interest:
	5658	5695	5732	5769	5806	5843	5880	5917

Email correspondence:
![image](https://user-images.githubusercontent.com/25047695/55429501-e89b2a00-5548-11e9-858f-4f2e02d24853.png)

**Comment by arocholl** [comment]
Please note zero span is different feature than looking for predefined frequencies. The zero span functionality returns a time-domain sweep, with multiple consecutive scan points over the same frequency. A predefined list of frequencies requires a different implementation than zero span, but we can try to make available both at the same time.
