### ISSUE TITLE
Modification of modules in Python in RFexplorer

### ISSUE THREAD

**Issue by realmerge** [RFExplorer/RFExplorer-for-Python#13]
I am trying to run RFexplorer with Python, but can I change module (15-2700 Mhz and 4.6 - 6.1 Ghz) on Python program?

**Comment by jcalderon09** [comment]
Hi, 
You can use _**​​​​SwitchModuleMain**_ and _**SwitchModuleExp**_ commands documented on [www.rf-explorer.com/API](https://github.com/RFExplorer/RFExplorer-for-.NET/wiki/RF-Explorer-UART-API-interface-specification) to switch between expansion and main board.

**Comment by realmerge** [comment]
Thank you for your reply.
I'm sorry for Python beginners, we are trying to measure with two bandwidths automatically using Python. How do I enter this command in a python program? Do you use subprocess, pexpect, etc?
