### ISSUE TITLE
Serial port autodetection

### ISSUE THREAD

**Issue by Goldthing** [RFExplorer/RFExplorer-for-Python#16]
Hi, I'm just getting started with the Python USB examples on OSX and I've hit a minor issue with autodetection. It appears as though the inbuilt Bluetooth serial port is detected as a valid option and then tried first and failing. Works fine if I change SERIALPORT variable to '/dev/cu.SLAB_USBtoUART'. See below for the output from my terminal

me$ python3 RFE_Example_USB_2.py
Detected COM ports:
  * /dev/cu.Bluetooth-Incoming-Port
  * /dev/cu.SLAB_USBtoUART
/dev/cu.Bluetooth-Incoming-Port is a valid available port.
/dev/cu.SLAB_USBtoUART is a valid available port.
RF Explorer Valid Ports found: 2 - /dev/cu.Bluetooth-Incoming-Port /dev/cu.SLAB_USBtoUART
User COM port: void
Error: select a different COM port
Not Connected

**Comment by arocholl** [comment]
Hi, thanks for your report. It does not make sense to get the Bluetooth detected as valid port, we will check where this may come from and fix as soon as possible.

**Comment by jcalderon09** [comment]
Hi @Goldthing, we have just released a new RFExplorer library v1.26.2001.1 with a better macOS driver identification to avoid false USB driver listing
