### ISSUE TITLE
Looking for help developing RF explorer application - Laptop/Tablet

### ISSUE THREAD

**Issue by trr549** [RFExplorer/RFExplorer-for-Python#19]
I am looking for a programmer to develop an application to capture data from the RF Explorer in real-time.  It can start simple.  I would like to enter a list of frequencies, identify a location on a floorplan (support for multiple floors is required), capture the peak of those frequencies at the location identified.  It would be nice to have a spectrum analyzer "window" to visually see activity.  Reporting functionality would be needed. 

Also, I am looking to develop a web-based RF heatmap simulation application for inside buildings.  

Thank you.

**Comment by arocholl** [comment]
We are currently developing a full Heatmap feature for the RF Explorer software, probably covering all your needs, we expect to have a first version ready before end of year. Let us know if you want to be a beta tester.

**Comment by trr549** [comment]
Yes. I would be interested in testing it but need to be careful if we
develop our own.

Question 1:  Can you customize and sell to us so we can sell under our
name?  We have public safety hardware and want complimentary hardware and
software only for the public safety market.

Question 2: What is your target price?

Thank you,
Tracy Richardson

**Comment by arocholl** [comment]
To discuss these details please create a ticket at https://support.rf-explorer.com so we check on your specific request.
