### ISSUE TITLE
Why the RFExplorer library must work under python3.5?

### ISSUE THREAD

**Issue by Lee-Kevin** [RFExplorer/RFExplorer-for-Python#2]
Why the RFExplorer library must work under python3.5, why can't worked under python3.4, as I know, some software like pyside isn't support python3.5 now. Can you provide suggestions about how to use PySide to make a GUI for RFExplorer?

Thanks

**Comment by arocholl** [comment]
Hi - thanks for your feedback.

Python 3.5 is the latest and suggested platform for Python development, including all important functional and security fixes.

There are plenty of options to create a GUI for RF Explorer, not only PySide. For instance you may want to check on this project started sometime ago by contributor: https://github.com/RFExplorer/pyRFExplorer using matplot
