### ISSUE TITLE
Support for RF Venue's RF Explorer Pro Audio Edition?

### ISSUE THREAD

**Issue by lee-richard-1** [RFExplorer/RFExplorer-for-Python#20]
Hello. I'm not too familiar with python or code, but during lockdown I've been trying to get higher resolution csv scans to use in Shure's WWB6 for RF Coordination of Microphones. I followed this video (https://www.youtube.com/watch?v=4yypnxZqxKc) but it wouldn't work. Then tried the example scripts in python and those don't work either. 
Would love if someone could update it so my version is supported. Thank you!

**Comment by lee-richard-1** [comment]
No?

**Comment by arocholl** [comment]
We have scheduled to include the additional models in the Python library in Q1

**Comment by arocholl** [comment]
You can get high resolution scans using RF Explorer Touch free download, you do not need python for that.

**Comment by lee-richard-1** [comment]
Amazing. Thank you
